version: '3'

services:

# Setup Server container

  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
      - ./server/src:/srv/app/api-server
    command: npm run start
    
# Setup Server container

  client: 
    build: ./client
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
      - ./client/src:/srv/app/frontend-client/src
      - ./client/public:/srv/app/frontend-client/public
    links:
      - server
    command: npm run start

